#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gexiv2
Version  : 0.12.0
Release  : 7
URL      : https://download.gnome.org/sources/gexiv2/0.12/gexiv2-0.12.0.tar.xz
Source0  : https://download.gnome.org/sources/gexiv2/0.12/gexiv2-0.12.0.tar.xz
Summary  : GObject bindings for exiv2
Group    : Development/Tools
License  : GPL-2.0
Requires: gexiv2-data = %{version}-%{release}
Requires: gexiv2-lib = %{version}-%{release}
Requires: gexiv2-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : exiv2-dev
BuildRequires : pygobject
BuildRequires : pygobject-python
BuildRequires : vala
BuildRequires : vala-dev

%description
gexiv2 - A GObject-based Exiv2 wrapper
--------------------------------------
* Introduction

%package data
Summary: data components for the gexiv2 package.
Group: Data

%description data
data components for the gexiv2 package.


%package dev
Summary: dev components for the gexiv2 package.
Group: Development
Requires: gexiv2-lib = %{version}-%{release}
Requires: gexiv2-data = %{version}-%{release}
Provides: gexiv2-devel = %{version}-%{release}
Requires: gexiv2 = %{version}-%{release}

%description dev
dev components for the gexiv2 package.


%package lib
Summary: lib components for the gexiv2 package.
Group: Libraries
Requires: gexiv2-data = %{version}-%{release}
Requires: gexiv2-license = %{version}-%{release}

%description lib
lib components for the gexiv2 package.


%package license
Summary: license components for the gexiv2 package.
Group: Default

%description license
license components for the gexiv2 package.


%prep
%setup -q -n gexiv2-0.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552352458
export LDFLAGS="${LDFLAGS} -fno-lto"
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dpython3_girdir=true  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gexiv2
cp COPYING %{buildroot}/usr/share/package-licenses/gexiv2/COPYING
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/true/GExiv2.py

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GExiv2-0.10.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gexiv2.deps
/usr/share/vala/vapi/gexiv2.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gexiv2/gexiv2-enums.h
/usr/include/gexiv2/gexiv2-log.h
/usr/include/gexiv2/gexiv2-managed-stream.h
/usr/include/gexiv2/gexiv2-metadata.h
/usr/include/gexiv2/gexiv2-preview-image.h
/usr/include/gexiv2/gexiv2-preview-properties.h
/usr/include/gexiv2/gexiv2-startup.h
/usr/include/gexiv2/gexiv2-version.h
/usr/include/gexiv2/gexiv2.h
/usr/lib64/libgexiv2.so
/usr/lib64/pkgconfig/gexiv2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgexiv2.so.2
/usr/lib64/libgexiv2.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gexiv2/COPYING
