#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gexiv2
Version  : 0.10.8
Release  : 4
URL      : https://download.gnome.org/sources/gexiv2/0.10/gexiv2-0.10.8.tar.xz
Source0  : https://download.gnome.org/sources/gexiv2/0.10/gexiv2-0.10.8.tar.xz
Summary  : GObject bindings for exiv2
Group    : Development/Tools
License  : GPL-2.0
Requires: gexiv2-lib
Requires: gexiv2-doc
Requires: gexiv2-data
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(exiv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pygobject-python
BuildRequires : python3

%description
gexiv2 - A GObject-based Exiv2 wrapper
--------------------------------------
* Introduction

%package data
Summary: data components for the gexiv2 package.
Group: Data

%description data
data components for the gexiv2 package.


%package dev
Summary: dev components for the gexiv2 package.
Group: Development
Requires: gexiv2-lib
Requires: gexiv2-data
Provides: gexiv2-devel

%description dev
dev components for the gexiv2 package.


%package doc
Summary: doc components for the gexiv2 package.
Group: Documentation

%description doc
doc components for the gexiv2 package.


%package lib
Summary: lib components for the gexiv2 package.
Group: Libraries
Requires: gexiv2-data

%description lib
lib components for the gexiv2 package.


%prep
%setup -q -n gexiv2-0.10.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518712100
%configure --disable-static --with-python3-girdir
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1518712100
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GExiv2-0.10.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/gexiv2/gexiv2-enums.h
/usr/include/gexiv2/gexiv2-log.h
/usr/include/gexiv2/gexiv2-managed-stream.h
/usr/include/gexiv2/gexiv2-metadata.h
/usr/include/gexiv2/gexiv2-preview-image.h
/usr/include/gexiv2/gexiv2-preview-properties.h
/usr/include/gexiv2/gexiv2-startup.h
/usr/include/gexiv2/gexiv2-version.h
/usr/include/gexiv2/gexiv2.h
/usr/lib64/libgexiv2.so
/usr/lib64/pkgconfig/gexiv2.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/gexiv2/GExiv2Metadata.html
/usr/share/gtk-doc/html/gexiv2/GExiv2PreviewImage.html
/usr/share/gtk-doc/html/gexiv2/GExiv2PreviewProperties.html
/usr/share/gtk-doc/html/gexiv2/annotation-glossary.html
/usr/share/gtk-doc/html/gexiv2/api-index-0-10-6.html
/usr/share/gtk-doc/html/gexiv2/api-index-full.html
/usr/share/gtk-doc/html/gexiv2/ch01.html
/usr/share/gtk-doc/html/gexiv2/deprecated-api-index.html
/usr/share/gtk-doc/html/gexiv2/gexiv2-Library-initialisation.html
/usr/share/gtk-doc/html/gexiv2/gexiv2-Logging-functionality.html
/usr/share/gtk-doc/html/gexiv2/gexiv2-gexiv2-version.html
/usr/share/gtk-doc/html/gexiv2/gexiv2.devhelp2
/usr/share/gtk-doc/html/gexiv2/home.png
/usr/share/gtk-doc/html/gexiv2/index.html
/usr/share/gtk-doc/html/gexiv2/left-insensitive.png
/usr/share/gtk-doc/html/gexiv2/left.png
/usr/share/gtk-doc/html/gexiv2/right-insensitive.png
/usr/share/gtk-doc/html/gexiv2/right.png
/usr/share/gtk-doc/html/gexiv2/style.css
/usr/share/gtk-doc/html/gexiv2/up-insensitive.png
/usr/share/gtk-doc/html/gexiv2/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgexiv2.so.2
/usr/lib64/libgexiv2.so.2.0.0
